### ISSUE TITLE
uninitialized constant Orats::Commands::New::FileUtils

### ISSUE THREAD

**Issue by ballPointPenguin** [nickjj/orats#29]
adding
```
require 'fileutils'
```
to the top of lib/orats/commands/new.rb seems to fix this for me

**Comment by nickjj** [comment]
Hi,

What version are you using, and what command did you run to produce this?

I just generated a few projects today and didn't see this pop up.

**Comment by ballPointPenguin** [comment]
I first observed this on my Linux machine, but today I am on MacOS and seeing the same thing:

```
➜  orats -v
orats version 5.1.1
➜  ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
➜  uname -a
Darwin MACC02Q6454G8WP 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64
```

When I run `orats new`:

```
➜  orats new vanilla

        task  Check if path exists

        task  Check if template exists

        task  Create 'base' project
        path  vanilla
/Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/orats-5.1.1/lib/orats/commands/new.rb:68:in `create_template': uninitialized constant Orats::Commands::New::FileUtils (NameError)
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/orats-5.1.1/lib/orats/commands/new.rb:20:in `init'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/orats-5.1.1/lib/orats/cli.rb:12:in `new'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/ben/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/orats-5.1.1/bin/orats:17:in `<top (required)>'
	from /Users/ben/.rbenv/versions/2.4.1/bin/orats:23:in `load'
	from /Users/ben/.rbenv/versions/2.4.1/bin/orats:23:in `<main>'
```

**Comment by nickjj** [comment]
That's interesting. I'm running the latest master locally and was able to generate a project.

In either case, I updated the gem to `v5.1.2` with your fix along with updating a few other things. It's available now.

Thanks!

**Comment by ballPointPenguin** [comment]
Works great. Thanks :)
