### ISSUE TITLE
New Rails app - Puma config not found

### ISSUE THREAD

**Issue by victorhazbun** [nickjj/orats#34]
I just created a new Rails application with this gem, then runned `docker-compose up --build`.

Log:

```
website_1   | /usr/local/bundle/gems/puma-3.11.2/lib/puma/dsl.rb:41:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/dsl.rb:41:in `_load_from'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:192:in `block in load'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:192:in `each'
cable_1     | ERROR: No application configured, nothing to run
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/configuration.rb:192:in `load'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/launcher.rb:59:in `initialize'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/cli.rb:68:in `new'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/lib/puma/cli.rb:68:in `initialize'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/bin/puma:8:in `new'
website_1   | 	from /usr/local/bundle/gems/puma-3.11.2/bin/puma:8:in `<top (required)>'
website_1   | 	from /usr/local/bundle/bin/puma:23:in `load'
website_1   | 	from /usr/local/bundle/bin/puma:23:in `<main>'
cable_1     | Puma starting in single mode...
cable_1     | * Version 3.11.2 (ruby 2.4.3-p205), codename: Love Song
cable_1     | * Min threads: 0, max threads: 16
cable_1     | * Environment: development
sidekiq_1   | 2018-02-19T03:02:18.016Z 1 TID-gtbg1z3z5 INFO: ==================================================================
sidekiq_1   | 2018-02-19T03:02:18.016Z 1 TID-gtbg1z3z5 INFO:   Please point sidekiq to a Rails 4/5 application or a Ruby file
sidekiq_1   | 2018-02-19T03:02:18.016Z 1 TID-gtbg1z3z5 INFO:   to load your worker classes with -r [DIR|FILE].
sidekiq_1   | 2018-02-19T03:02:18.016Z 1 TID-gtbg1z3z5 INFO: ==================================================================
sidekiq_1   | 2018-02-19T03:02:18.016Z 1 TID-gtbg1z3z5 INFO: sidekiq [options]
sidekiq_1   |     -c, --concurrency INT            processor threads to use
sidekiq_1   |     -d, --daemon                     Daemonize process
sidekiq_1   |     -e, --environment ENV            Application environment
sidekiq_1   |     -g, --tag TAG                    Process tag for procline
sidekiq_1   |     -i, --index INT                  unique process index on this machine
sidekiq_1   |     -q, --queue QUEUE[,WEIGHT]       Queues to process with optional weights
sidekiq_1   |     -r, --require [PATH|DIR]         Location of Rails application with workers or file to require
sidekiq_1   |     -t, --timeout NUM                Shutdown timeout
sidekiq_1   |     -v, --verbose                    Print more verbose output
sidekiq_1   |     -C, --config PATH                path to YAML config file
sidekiq_1   |     -L, --logfile PATH               path to writable logfile
sidekiq_1   |     -P, --pidfile PATH               path to pidfile
sidekiq_1   |     -V, --version                    Print version and exit
sidekiq_1   |     -h, --help                       Show help
sidekiq_1   |
twitalytics_website_1 exited with code 1
twitalytics_sidekiq_1 exited with code 1
twitalytics_cable_1 exited with code 1
```

**Comment by victorhazbun** [comment]
Hey, please excuse me. I created a new Rails app with the gem and now it works.

**Comment by nickjj** [comment]
Ok, I'm closing this because I'm thinking something changed in the first app that you made which is unrelated to what this gem produces.
